name: LinuxServer-Changedetection.io
services:
  app:
    image: linuxserver/changedetection.io:0.42.2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: BASE_URL
          description:
            en_us: Specify the full URL (including protocol) when running behind a reverse proxy
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/changedetection.io/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Changedetection.io provides free, open-source web page monitoring, notification and change detection.
  tagline:
    en_us: Provides Free, Open-source Web Page Monitoring, Notification And Change Detection.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/changedetection-icon.png
  thumbnail: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/changedetection-icon.png
  title:
    en_us: Changedetection.io
  category: LinuxServer.io
