name: LinuxServer-Code-server
services:
  app:
    image: linuxserver/code-server:4.13.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
      HASHED_PASSWORD: ''
      SUDO_PASSWORD: ''
      SUDO_PASSWORD_HASH: ''
      PROXY_DOMAIN: ''
      DEFAULT_WORKSPACE: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: PASSWORD
          description:
            en_us: Optional web gui password, if PASSWORD or HASHED_PASSWORD is not provided, there will be no auth.
        - container: HASHED_PASSWORD
          description:
            en_us: Optional web gui password, overrides PASSWORD, instructions on how to create it is below.
        - container: SUDO_PASSWORD
          description:
            en_us: If this optional variable is set, user will have sudo access in the code-server terminal with the specified password.
        - container: SUDO_PASSWORD_HASH
          description:
            en_us: Optionally set sudo password via hash (takes priority over SUDO_PASSWORD var). Format is $type$salt$hashed.
        - container: PROXY_DOMAIN
          description:
            en_us: If this optional variable is set, this domain will be proxied for subdomain proxying. See Documentation
        - container: DEFAULT_WORKSPACE
          description:
            en_us: If this optional variable is set, code-server will open this directory by default
      volumes:
        - container: /config
          description:
            en_us: Appdata - /config
      ports:
        - container: '8443'
          description:
            en_us: Webui Port - Default 8443
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/code-server/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/code-server/'
  tagline:
    en_us: Vs Code Running On A Remote Server, Accessible Through The Browser. - Code On Your Chromebook, Tablet, And Laptop With A Consistent Dev Environment. - If You Have A Windows Or Mac Workstation, More Easily Develop For Linux. - Take Advantage Of Large Cloud Servers To Speed Up Tests, Compilations, Downloads, And More. - Preserve Battery Life When You're On The Go. - All Intensive Computation Runs On Your Server. - You're No Longer Running Excess Instances Of Chrome.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/code-server.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/code-server-banner.png
  title:
    en_us: Code Server
  category: LinuxServer.io
  port_map: '8443'
