name: LinuxServer-Wireshark
services:
  app:
    image: linuxserver/wireshark:4.0.6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
      volumes:
        - container: /config
          description:
            en_us: Appdata
      ports: []
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wireshark/config
        target: /config
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/wireshark/'
  tagline:
    en_us: The World’s Foremost And Widely-used Network Protocol Analyzer. It Lets You See What’s Happening On Your Network At A Microscopic Level And Is The De Facto (and Often De Jure) Standard Across Many Commercial And Non-profit Enterprises, Government Agencies, And Educational Institutions. Wireshark Development Thrives Thanks To The Volunteer Contributions Of Networking Experts Around The Globe And Is The Continuation Of A Project Started By Gerald Combs In 1998.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/wireshark-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/wireshark-icon.png
  title:
    en_us: Wireshark
  category: LinuxServer.io
  port_map: '3000'
