name: LinuxServer-Airsonic-advanced
services:
  app:
    image: linuxserver/airsonic-advanced:11.0.0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONTEXT_PATH: ''
      JAVA_OPTS: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: CONTEXT_PATH
          description:
            en_us: For setting url-base in reverse proxy setups.
        - container: JAVA_OPTS
          description:
            en_us: For passing additional java options.
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /music
          description:
            en_us: 'Container Path: /music'
        - container: /playlists
          description:
            en_us: 'Container Path: /playlists'
        - container: /podcasts
          description:
            en_us: 'Container Path: /podcasts'
        - container: /media
          description:
            en_us: 'Container Path: /media'
      ports:
        - container: '4040'
          description:
            en_us: 'Container Port: 4040'
    ports:
      - target: 4040
        published: 4040
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/airsonic-advanced/config
        target: /config
      - type: bind
        source: /DATA/AppData/airsonic-advanced/music
        target: /music
      - type: bind
        source: /DATA/AppData/airsonic-advanced/playlists
        target: /playlists
      - type: bind
        source: /DATA/AppData/airsonic-advanced/podcasts
        target: /podcasts
      - type: bind
        source: /DATA/AppData/airsonic-advanced/media
        target: /media
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/airsonic/'
  tagline:
    en_us: A Free, Web-based Media Streamer, Providing Ubiquitious Access To Your Music. Use It To Share Your Music With Friends, Or To Listen To Your Own Music While At Work. You Can Stream To Multiple Players Simultaneously, For Instance To One Player In Your Kitchen And Another In Your Living Room.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/airsonic-logo.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/airsonic-banner.png
  title:
    en_us: Airsonic Advanced
  category: LinuxServer.io
  port_map: '4040'
  index: /airsonic
